[project]
name = "inference-modules-transformers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "llm-jp-eval-inference",
    "torch>=2.4.0",
    "transformers>=4.45.1,<4.46.0",
    "vllm==0.6.2",
    "vllm-flash-attn"
]

[tool.uv.sources]
llm-jp-eval-inference = { path = "../../", editable = true }
