run_name: null  # This value will be applied to both offline_inference.run_name and wandb.run_name with the highest priority.

wandb:
  launch: false
  entity: entity
  project: project

tokenize_kwargs:
  add_special_tokens: true

prompt_json_path: '../../../local_files/datasets/2.0.0/evaluation/path/to/prompts/*.eval-prompt.json'